# Site settings
title: VizSec
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The IEEE Symposium on Visualization for Cyber Security (VizSec) is a forum that brings together researchers and practitioners from academia, government, and industry to address the needs of the cybersecurity community through new and insightful visualization and analysis techniques. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vizsec.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

collections:
    - vizsecmeta

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
